# 异常 
异常：是在运行时期发生的不正常情况  
在Java中用类的形式对不正常情况进行了描述和封装对象  
描述不正常情况的类，就称为异常类  

以前，正常流程代码和问题处理代码相结合  
现在，将正常流程代码和问题处理代码分离，提高阅读性  

其实异常就是Java通过面向对象的思想将问题封装成对象  
用异常类对其进行描述  
不同的问题用不同的类进行具体的描述。比如，角标越界、空指针等  

问题很多，意味着描述的类也很多，将其共性进行向上抽取，形成了 **异常体系**  

## 异常体系
最终问题(不正常情况)就分成了两大类  
Throwable：  
>   一般不可处理的 Error  
    是由JVM抛出的严重性问题，这种问题一般不针对性处理，直接修改程序  
>   可处理的 Exception

无论是Error，还是异常问题，问题发生就应该可以抛出，让调用者知道并处理  
该体系的特点就在于Throwable及其所有的子类都具有 **可抛性**  

### 可抛性指的是什么？怎么体现可抛性？
其实是通过两个关键字来体现的。**throw**，**throws**  
凡是可以被这两个关键字所操作的类和对象都具备可抛性  

该体系的特点：子类的后缀名都是用其父类名作为后缀，阅读性很强  

### 自定义异常  
某些异常在Java中没有定义过，那么就按照Java异常的创建思想，面向对象，进行自定义描述，并封装成对象  
注意：如果让一个类称为异常类，必须要继承异常体系，因为只有成为异常体系的子类，才有资格具备可抛性，才可以被两个关键字所操作  

## 异常的分类  
1.  编译时被检测异常：只有是，Exception和其子类都是，除了特殊子类RuntimeException体系  
    这种问题一旦出现，希望在编译时就进行检测，让这种问题有应对的处理方式，这样的问题都可以进行针对性处理  
2.  编译时不检测异常(运行时异常) 就是Exception中的RuntimeException和其子类  
    这种问题的发生，无法让功能继续，运算无法进行，更多是因为调用者的原因导致的，或者引发了内部状态的改变导致的，那么这种问题一般不处理，直接编译通过。在运行时，让调用者调用时的程序强制停止，让调用者对代码进行修正  

所以自定义异常时，要么继承Exception，要么继承RuntimeException  

### throws和throw的区别  
1. throws使用在函数声明上，throw使用在函数内  
2. throws抛出的是异常类，可抛出多个，用逗号隔开；throw抛出的是异常对象  

异常出现时，一般需要对异常进行声明或捕捉  
```java
class Demo {
    public int method(参数) throws Exception {
        if(参数满足条件) {
            throw new Exception(); // new一个异常类的对象
        }
    }
}
// 如果函数中发生异常，需要在函数上进行声明，否则定义失败，throws抛出 也是声明的一种处理方法  
```
## 异常的处理
### 如何进行异常的捕捉  
异常处理的捕捉形式，这是可以对异常进行针对性处理的方式  
```java
try {
    // 需要被检测异常的代码块
} catch (异常类名 变量e) {
    // 该变量用于接收发生的异常对象
    // 此处写处理异常的代码
} finally {
    // 一定会被执行的代码，不论异常是否处理
}
// 处理异常代码时，由于变量是接收异常对象的，所以可以用调用异常对象的方法，达到处理目的
// e.getMessage:获取异常信息  
// System.out.println(e):异常对象独特的字符串表现形式。一般对象时哈希值及类型，异常对象是异常信息，默认调用了toString()方法  
// e.printStackTrace():输出堆栈跟踪信息，JVM默认的异常处理机制就是调用异常对象的这个方法  
```
#### 多catch情况
```java
try {

} catch(异常一 变量e1) {

} catch(异常二 变量e2) {
    
} catch(Exception 变量e) {
    
}
// 若异常父类放在最前面第一个catch上，后面的子类都不会运行，导致编译失败  
// Exception是所有异常的父类，所以要把它放在最后，异常没有被捕获是，均由Exception捕获
```
### 异常处理的原则
1. 函数内容如果抛出要检测的异常，那么函数上必须要声明。否则必须在函数内用try...catch捕捉，否则编译失败  
2. 如果滴啊用了声明异常的函数，要么try...catch，要么throws，否则编译失败  
3. 什么时候catch，什么时候throws呢？
   功能内容可以解决，用catch  
   解决不了，用throws告诉调用者，由调用者解决  
4. 一个功能如果抛出了多个异常，那么调用时，必须对应多个catch进行针对性处理  
   内部有几个需要检测的异常，就抛出几个异常，抛出几个就catch几个  

### finally 代码块
```java
finally {
    // 通常用于关闭(释放)资源
}
```
### try catch finally代码块组合特点
1. try catch finally 正常模式  
2. try catch(多个) 当没有必要的资源需要释放时，可以不用定义finally  
3. try finally 异常无法直接处理，但是资源需要关闭  

### 异常的注意事项
1. 子类在覆盖父类方法时，父类的方法如果抛出了异常，那么子类的方法只能抛出父类的异常或者该异常的子类  
2. 如果父类抛出了多个异常，那么子类只能抛出父类异常的子集。  
注意：如果父类的方法 *没有抛出异常*，那么子 类覆盖时 **绝对不能抛出异常**，就只能try...catch操作